<?php

declare(strict_types=1);

namespace GutenbergDowngrade;

use RuntimeException;

/**
 * Builds the manifest array from an assembled asset tree. Pure PHP (no
 * WordPress): it runs at build time inside the Nix sandbox and in the
 * `manifest` check, and Manifest::load() validates its output at runtime.
 *
 * @phpstan-import-type ManifestArray from Manifest
 * @phpstan-import-type PackageEntry from Manifest
 * @phpstan-import-type BlockEntry from Manifest
 */
final class ManifestGenerator
{
    /** Where the release keeps block.json folders and the dynamic-block PHP next to them. */
    private const BLOCK_ROOTS = [
        'build/block-library/blocks',
        'build/widgets/blocks',
    ];

    /**
     * @return ManifestArray
     */
    public static function generate(string $assetsDir, string $gutenbergVersion): array
    {
        if (!is_dir($assetsDir . '/build')) {
            throw new RuntimeException("{$assetsDir}/build does not exist");
        }

        return [
            'gutenbergVersion' => $gutenbergVersion,
            'packages'         => self::packages($assetsDir),
            'blocks'           => self::blocks($assetsDir),
            'vendor'           => self::vendor($assetsDir),
        ];
    }

    /**
     * Serialise as a PHP file with stable ordering, so the `manifest` check can
     * diff a regenerated copy against the shipped one.
     *
     * @param ManifestArray $manifest
     */
    public static function render(array $manifest): string
    {
        $export = var_export($manifest, true);
        // var_export() emits `array (` / `NULL`; normalise to the short forms
        // PSR-12 tooling expects so the file is readable in diffs.
        $export = (string) preg_replace('/^(\s*)array \(/m', '$1[', $export);
        $export = (string) preg_replace('/^(\s*)\),/m', '$1],', $export);
        $export = (string) preg_replace('/\)$/', ']', $export);
        $export = str_replace('NULL', 'null', $export);

        return "<?php\n\n"
            . "/**\n"
            . " * Generated by bin/generate-manifest.php — do not edit.\n"
            . " *\n"
            . " * Gutenberg {$manifest['gutenbergVersion']} asset inventory read by GutenbergDowngrade\\Manifest.\n"
            . " */\n\n"
            . "declare(strict_types=1);\n\n"
            . "return {$export};\n";
    }

    /**
     * @return array<string, PackageEntry>
     */
    private static function packages(string $assetsDir): array
    {
        $packages = [];
        $assetFiles = glob($assetsDir . '/build/*/index.min.asset.php') ?: [];

        foreach ($assetFiles as $assetFile) {
            $dir = basename(dirname($assetFile));
            $handle = 'wp-' . $dir;
            $relativeDir = 'build/' . $dir;

            /** @var mixed $asset */
            $asset = require $assetFile;
            if (
                !is_array($asset)
                || !isset($asset['dependencies'], $asset['version'])
                || !is_array($asset['dependencies'])
                || !is_string($asset['version'])
            ) {
                throw new RuntimeException("{$assetFile} is not a valid asset file");
            }

            $deps = [];
            foreach ($asset['dependencies'] as $dep) {
                if (!is_string($dep)) {
                    throw new RuntimeException("{$assetFile} lists a non-string dependency");
                }
                $deps[] = $dep;
            }

            $js = $relativeDir . '/index.min.js';
            self::requireFile($assetsDir, $js);
            $jsDebug = $relativeDir . '/index.js';

            $packages[$handle] = [
                'js'      => $js,
                'jsDebug' => is_file($assetsDir . '/' . $jsDebug) ? $jsDebug : null,
                'deps'    => $deps,
                'version' => $asset['version'],
            ];
        }

        if ($packages === []) {
            throw new RuntimeException("no build/*/index.min.asset.php files under {$assetsDir}");
        }

        ksort($packages);

        return $packages;
    }

    /**
     * @return array<string, BlockEntry>
     */
    private static function blocks(string $assetsDir): array
    {
        $blocks = [];

        foreach (self::BLOCK_ROOTS as $root) {
            $jsonFiles = glob($assetsDir . '/' . $root . '/*/block.json') ?: [];

            foreach ($jsonFiles as $jsonFile) {
                $folder = basename(dirname($jsonFile));
                $raw = file_get_contents($jsonFile);
                $metadata = is_string($raw) ? json_decode($raw, true) : null;

                if (!is_array($metadata) || !isset($metadata['name']) || !is_string($metadata['name'])) {
                    throw new RuntimeException("{$jsonFile} has no block name");
                }

                $name = $metadata['name'];
                if (isset($blocks[$name])) {
                    throw new RuntimeException("block {$name} is defined twice");
                }

                $php = $root . '/' . $folder . '.php';

                $blocks[$name] = [
                    'dir' => $root . '/' . $folder,
                    'php' => is_file($assetsDir . '/' . $php) ? $php : null,
                ];
            }
        }

        if ($blocks === []) {
            throw new RuntimeException("no block.json files under {$assetsDir}");
        }

        ksort($blocks);

        return $blocks;
    }

    /**
     * @return array{react: array{prod: string, dev: string}, react-dom: array{prod: string, dev: string}}
     */
    private static function vendor(string $assetsDir): array
    {
        foreach (['vendor/react.min.js', 'vendor/react.js', 'vendor/react-dom.min.js', 'vendor/react-dom.js'] as $file) {
            self::requireFile($assetsDir, $file);
        }

        return [
            'react'     => ['prod' => 'vendor/react.min.js', 'dev' => 'vendor/react.js'],
            'react-dom' => ['prod' => 'vendor/react-dom.min.js', 'dev' => 'vendor/react-dom.js'],
        ];
    }

    private static function requireFile(string $assetsDir, string $relative): void
    {
        if (!is_file($assetsDir . '/' . $relative)) {
            throw new RuntimeException("expected file is missing: {$relative}");
        }
    }
}
